import configparser
import os
import sqlite3
import subprocess
import sys
import time
import uuid
from datetime import datetime
from pathlib import Path

import pytest
import requests

from edition import feature_enabled
from enterprise.challenge_passwords import build_challenge_password_view
from enterprise.tokens import create_api_token
from extensions import db
from user_models import create_user_db, get_user_by_username
from x509_keys import Key


ROOT_DIR = Path(__file__).resolve().parents[1]
SCRIPTS_DIR = ROOT_DIR / "tests" / "scripts"
EDITION = (os.getenv("PIKACHU_EDITION") or "community").strip().lower()


def _is_enterprise():
    return EDITION == "enterprise"


def _login(client, username, password):
    return client.post(
        "/users/login",
        data={"username": username, "password": password},
        follow_redirects=True,
    )


def _ensure_user(app, username, password, role="user"):
    with app.app_context():
        user = get_user_by_username(username)
        if user is None:
            create_user_db(username, password, role=role, status="active")


@pytest.fixture(scope="session", autouse=True)
def cleanup_api_artifacts():
    """
    After API tests run, delete test artifacts generated by the PowerShell scripts.
    """
    yield
    # Give external observers a brief window before cleanup kicks in
    time.sleep(20)
    patterns = [
        ROOT_DIR / "tests" / "results" / "*.crt",
        ROOT_DIR / "tests" / "results" / "*.csr",
        ROOT_DIR / "tests" / "results" / "*.key",
        ROOT_DIR / "tests" / "estclient" / "etx-estclient.*",
        ROOT_DIR / "tests" / "estclient" / "pikachu_issued_https_pkcs8.key",
    ]
    for pat in patterns:
        for path in pat.parent.glob(pat.name):
            try:
                path.unlink()
            except Exception:
                pass
    # DB cleanup: remove test certificates generated by API scripts
    try:
        cfg = configparser.ConfigParser()
        cfg.read(ROOT_DIR / "config.ini")
        db_rel = cfg.get("PATHS", "db_path", fallback="PKI.db")
        db_path = ROOT_DIR / db_rel
        if db_path.exists():
            patterns = [
                "%sscep-test-%",
                "%sscep-test-pass-%",
                "%estclient-go-%",
                "%estclient-go-mtls-%",
            ]
            with sqlite3.connect(db_path) as conn:
                for p in patterns:
                    conn.execute("DELETE FROM certificates WHERE subject LIKE ?", (p,))
                conn.commit()
    except Exception:
        pass


def _run_ps_script(script_name, args=(), timeout=240):
    script_path = SCRIPTS_DIR / script_name
    if not script_path.exists():
        pytest.skip(f"Script not found: {script_path}")
    cmd = [
        "powershell",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(script_path),
        *[str(a) for a in args],
    ]
    proc = subprocess.run(
        cmd,
        cwd=ROOT_DIR,
        capture_output=True,
        text=True,
        timeout=timeout,
    )
    return proc


def _combined_output(proc: subprocess.CompletedProcess) -> str:
    return (proc.stdout or "") + "\n" + (proc.stderr or "")


def _skip_if_missing_tool(proc: subprocess.CompletedProcess, keywords):
    # Only consider skipping when the script failed
    if proc.returncode == 0:
        return
    output = _combined_output(proc).lower()
    failure_markers = [
        "not recognized",
        "not found",
        "no such file",
        "could not find",
        "missing",
        "is not installed",
        "command not found",
    ]
    for kw in keywords:
        if kw.lower() in output:
            if any(marker in output for marker in failure_markers):
                pytest.skip(f"Missing prerequisite/tool: {kw}")


def _attach_output(request, name: str, proc: subprocess.CompletedProcess):
    """Attach script output to pytest-html report if plugin is present."""
    pytest_html = request.config.pluginmanager.getplugin("html")
    if not pytest_html:
        return
    extra = getattr(request.node, "extra", [])
    content = _combined_output(proc)
    extra.append(pytest_html.extras.text(content, name=name))
    request.node.extra = extra


def _emit_and_attach(request, name: str, proc: subprocess.CompletedProcess) -> str:
    """Print script output (for pytest-html logs) and attach as extra."""
    output = _combined_output(proc)
    print(f"\n--- {name} ---\n{output}\n--- end {name} ---\n")
    _attach_output(request, name, proc)
    return output


def test_api_basic_endpoints(request):
    """Run basic API checks (CA chain, CRL, status, CSR download)."""
    proc = _run_ps_script("test_basic.ps1", timeout=180)
    _emit_and_attach(request, "test_basic.ps1 output", proc)
    if proc.returncode != 0:
        pytest.fail(f"test_basic.ps1 failed:\n{_combined_output(proc)}")


def test_est_enrollment_via_estclient_go(request):
    """EST enrollment using estclient-go (non-mTLS)."""
    if not _is_enterprise():
        pytest.skip("EST is enterprise-only in community mode")
    proc = _run_ps_script("test_estclient_go.ps1", timeout=240)
    _skip_if_missing_tool(proc, ["estclient", "wsl"])
    _emit_and_attach(request, "test_estclient_go.ps1 output", proc)
    if proc.returncode != 0:
        pytest.fail(f"test_estclient_go.ps1 failed:\n{_combined_output(proc)}")


def test_est_enrollment_via_estclient_go_mtls(request):
    """EST enrollment using estclient-go with mTLS."""
    if not _is_enterprise():
        pytest.skip("EST mTLS is enterprise-only in community mode")
    proc = _run_ps_script("test_estclient_go_mtls.ps1", timeout=240)
    _skip_if_missing_tool(proc, ["estclient", "wsl"])
    _emit_and_attach(request, "test_estclient_go_mtls.ps1 output", proc)
    if proc.returncode != 0:
        pytest.fail(f"test_estclient_go_mtls.ps1 failed:\n{_combined_output(proc)}")


def test_sscep_core(request):
    """SCEP tests without challenge password (sscep.exe)."""
    if not _is_enterprise():
        pytest.skip("SCEP is enterprise-only in community mode")
    proc = _run_ps_script("test_sscep.ps1", timeout=180)
    _skip_if_missing_tool(proc, ["sscep.exe", "openssl"])
    _emit_and_attach(request, "test_sscep.ps1 output", proc)
    if proc.returncode != 0:
        pytest.fail(f"test_sscep.ps1 failed:\n{_combined_output(proc)}")


def _generate_challenge_password(usage_mode="single_use", validity=None):
    cfg = configparser.ConfigParser()
    cfg.read(ROOT_DIR / "config.ini")
    http_port = cfg.get("DEFAULT", "http_port", fallback="80")
    challenge_enabled = cfg.getboolean("SCEP", "challenge_password_enabled", fallback=False)
    if not challenge_enabled:
        return ""
    token = cfg.get("DEFAULT", "tests_api_token", fallback="").strip()
    if not token:
        return "NO_TOKEN"

    base_url = f"http://127.0.0.1:{http_port}"
    payload = {"usage_mode": usage_mode}
    if validity:
        payload["validity"] = validity
    try:
        resp = requests.post(
            f"{base_url}/api/challenge_passwords",
            headers={"Authorization": f"Bearer {token}"},
            json=payload,
            timeout=20,
        )
    except Exception as e:
        return f"REQ_FAILED:{e}"

    if resp.status_code != 201:
        return f"API_FAILED:{resp.status_code}:{resp.text[:200]}"

    try:
        data = resp.json()
    except Exception:
        return "PARSE_FAILED"

    if not data.get("value"):
        return "EMPTY_PASSWORD"
    return data


def _load_challenge_password_row(value):
    cfg = configparser.ConfigParser()
    cfg.read(ROOT_DIR / "config.ini")
    db_rel = cfg.get("PATHS", "db_path", fallback="PKI.db")
    db_path = ROOT_DIR / db_rel
    with sqlite3.connect(db_path) as conn:
        conn.row_factory = sqlite3.Row
        row = conn.execute(
            """
            SELECT value, user_id, created_at, validity, consumed, usage_mode, use_count, last_used_at
            FROM challenge_passwords
            WHERE value = ?
            """,
            (value,),
        ).fetchone()
    assert row is not None, f"Challenge password {value} not found in DB"
    return row


def _run_sscep_with_password(request, challenge_value, output_name):
    proc = _run_ps_script("test_sscep_pass.ps1", args=[challenge_value], timeout=180)
    output = _emit_and_attach(request, output_name, proc)
    _skip_if_missing_tool(proc, ["sscep.exe", "openssl"])
    if proc.returncode != 0:
        pytest.fail(f"{output_name} failed:\n{output}")
    return output


def test_sscep_with_challenge_password(request):
    """SCEP tests with challenge password (sscep.exe + challenge)."""
    if not _is_enterprise():
        pytest.skip("SCEP challenge password is enterprise-only in community mode")
    challenge = _generate_challenge_password()
    if not isinstance(challenge, dict):
        pytest.skip(f"Could not generate challenge password ({challenge})")
    _run_sscep_with_password(request, challenge["value"], "test_sscep_pass.ps1 output")
    row = _load_challenge_password_row(challenge["value"])
    assert row["usage_mode"] == "single_use"
    assert row["consumed"] == 1
    assert row["use_count"] >= 1
    view = build_challenge_password_view(row)
    assert view["status_label"] == "Consumed"


def test_sscep_with_reusable_challenge_password_can_enroll_twice(request):
    """SCEP reusable challenge password should allow multiple enrollments."""
    if not _is_enterprise():
        pytest.skip("SCEP challenge password is enterprise-only in community mode")
    challenge = _generate_challenge_password(usage_mode="reusable", validity="30m")
    if not isinstance(challenge, dict):
        pytest.skip(f"Could not generate reusable challenge password ({challenge})")
    _run_sscep_with_password(request, challenge["value"], "test_sscep_pass_reusable_1.ps1 output")
    _run_sscep_with_password(request, challenge["value"], "test_sscep_pass_reusable_2.ps1 output")
    row = _load_challenge_password_row(challenge["value"])
    assert row["usage_mode"] == "reusable"
    assert row["consumed"] == 0
    assert row["use_count"] >= 2
    assert row["last_used_at"]
    view = build_challenge_password_view(row)
    assert view["status_label"] == "Used - Reusable"


def test_sscep_with_unlimited_challenge_password_can_enroll_twice(request):
    """SCEP unlimited challenge password should allow repeated enrollments without expiry."""
    if not _is_enterprise():
        pytest.skip("SCEP challenge password is enterprise-only in community mode")
    challenge = _generate_challenge_password(usage_mode="reusable_unlimited")
    if not isinstance(challenge, dict):
        pytest.skip(f"Could not generate unlimited challenge password ({challenge})")
    _run_sscep_with_password(request, challenge["value"], "test_sscep_pass_unlimited_1.ps1 output")
    _run_sscep_with_password(request, challenge["value"], "test_sscep_pass_unlimited_2.ps1 output")
    row = _load_challenge_password_row(challenge["value"])
    assert row["usage_mode"] == "reusable_unlimited"
    assert row["consumed"] == 0
    assert row["use_count"] >= 2
    assert row["validity"] in (None, "")
    view = build_challenge_password_view(row)
    assert view["status_label"] == "Used - Unlimited"


def test_enterprise_endpoint_est_present(client):
    """Edition-aware check for EST endpoint."""
    resp = client.get("/.well-known/est/cacerts")
    if _is_enterprise():
        assert resp.status_code != 404, "EST endpoint is unavailable in enterprise mode"
    else:
        assert resp.status_code == 404, "EST endpoint should be blocked in community mode"


def test_enterprise_endpoint_scep_present(client):
    """Edition-aware check for SCEP endpoint."""
    resp = client.get("/scep?operation=GetCACaps")
    if _is_enterprise():
        assert resp.status_code != 404, "SCEP endpoint is unavailable in enterprise mode"
    else:
        assert resp.status_code == 404, "SCEP endpoint should be blocked in community mode"


def test_enterprise_endpoint_ocsp_present(client):
    """Edition-aware check for OCSP endpoint."""
    resp = client.get("/ocsp")
    if _is_enterprise():
        assert resp.status_code != 404, "OCSP endpoint is unavailable in enterprise mode"
    else:
        assert resp.status_code == 404, "OCSP endpoint should be blocked in community mode"


@pytest.mark.skipif(not feature_enabled("api_tokens"), reason="API tokens are enterprise-only")
def test_key_api_get_material_by_name_with_api_token(client, app):
    _ensure_user(app, "user", "userpass", role="user")

    _login(client, "user", "userpass")
    client.post("/generate", data={"key_type": "RSA", "key_name": "api-key-test"}, follow_redirects=True)

    with app.app_context():
        user = get_user_by_username("user")
        assert user is not None
        key_obj = Key.query.filter_by(name="api-key-test", user_id=user.id).order_by(Key.id.desc()).first()
        assert key_obj is not None
        raw_token, _ = create_api_token(user.id, "keys-api-test-token", validity="1d")

    headers = {"Authorization": f"Bearer {raw_token}"}

    private_resp = client.get("/api/keys/api-key-test/private", headers=headers, base_url="https://localhost:4443")
    assert private_resp.status_code == 200
    assert b"BEGIN PRIVATE KEY" in private_resp.data or b"BEGIN RSA PRIVATE KEY" in private_resp.data
    assert private_resp.headers.get("X-Key-Name") == "api-key-test"

    public_resp = client.get("/api/keys/api-key-test/public", headers=headers, base_url="https://localhost:4443")
    assert public_resp.status_code == 200
    assert b"BEGIN PUBLIC KEY" in public_resp.data
    assert public_resp.headers.get("X-Key-Name") == "api-key-test"


@pytest.mark.skipif(not feature_enabled("api_tokens"), reason="API tokens are enterprise-only")
def test_key_api_requires_token(client):
    resp = client.get("/api/keys/missing/private", base_url="https://localhost:4443")
    assert resp.status_code == 401
    assert resp.is_json
    assert resp.get_json()["error"] == "API token required"


@pytest.mark.skipif(not feature_enabled("api_tokens"), reason="API tokens are enterprise-only")
def test_key_api_allows_normal_https_port(client, app):
    username = f"https_user_{uuid.uuid4().hex[:8]}"
    key_name = f"https-key-{uuid.uuid4().hex[:8]}"
    public_pem = "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtesttesttesttesttesttest\n-----END PUBLIC KEY-----\n"
    private_pem = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDtesttesttesttest\n-----END PRIVATE KEY-----\n"
    _ensure_user(app, username, "httpspass", role="user")

    with app.app_context():
        https_user = get_user_by_username(username)
        assert https_user is not None
        db.session.add(
            Key(
                name=key_name,
                key_type="RSA",
                key_size=2048,
                private_key=private_pem,
                public_key=public_pem,
                created_at=datetime.utcnow(),
                user_id=https_user.id,
            )
        )
        db.session.commit()
        raw_token, _ = create_api_token(https_user.id, "https-token", validity="1d")

    resp = client.get(
        f"/api/keys/{key_name}/public",
        headers={"Authorization": f"Bearer {raw_token}"},
        base_url="https://localhost:443",
    )
    assert resp.status_code == 200
    assert b"BEGIN PUBLIC KEY" in resp.data


@pytest.mark.skipif(not feature_enabled("api_tokens"), reason="API tokens are enterprise-only")
def test_key_api_user_token_cannot_access_other_users_key(client, app):
    _ensure_user(app, "alice", "alicepass", role="user")
    _ensure_user(app, "bob", "bobpass", role="user")

    _login(client, "alice", "alicepass")
    client.post("/generate", data={"key_type": "RSA", "key_name": "alice-only-key"}, follow_redirects=True)

    with app.app_context():
        bob = get_user_by_username("bob")
        assert bob is not None
        bob_token, _ = create_api_token(bob.id, "bob-token", validity="1d")

    resp = client.get(
        "/api/keys/alice-only-key/private",
        headers={"Authorization": f"Bearer {bob_token}"},
        base_url="https://localhost:4443",
    )
    assert resp.status_code == 404
    assert resp.is_json
    assert resp.get_json()["error"] == "Key 'alice-only-key' not found"


@pytest.mark.skipif(not feature_enabled("api_tokens"), reason="API tokens are enterprise-only")
def test_key_api_admin_token_can_access_other_users_key(client, app):
    _ensure_user(app, "carol", "carolpass", role="user")
    _ensure_user(app, "admin_api", "adminpass", role="admin")

    _login(client, "carol", "carolpass")
    client.post("/generate", data={"key_type": "RSA", "key_name": "carol-key"}, follow_redirects=True)

    with app.app_context():
        admin_user = get_user_by_username("admin_api")
        assert admin_user is not None
        admin_token, _ = create_api_token(admin_user.id, "admin-token", validity="1d")

    resp = client.get(
        "/api/keys/carol-key/public",
        headers={"Authorization": f"Bearer {admin_token}"},
        base_url="https://localhost:4443",
    )
    assert resp.status_code == 200
    assert b"BEGIN PUBLIC KEY" in resp.data
